<?php
$title = 'Project Skyhook&trade; Bitcoin ATM';
$styles = [
	'/assets/Messi/messi.css',
	'/assets/css/skyhook.css',
];
$currencyMeta = $config->getCurrencyMeta();
$classes = ['purchase'];
include '../head.phtml';
?>
<button id="canceler">
	&times;
</button>
<div id="help-panel">
	<?= file_get_contents(Localization::path("help.html")); ?>
	<a href="#" class="closer button">&times;</a>
</div>
<div class="purchase-content">
	<div class="price">
		<div class="crypto-amount">1 <?= $i18n->_('bitcoin') ?></div>
		<div class="fiat-amount"><?= $currencyMeta->format($ticket->getBitcoinPrice(), true) ?></div>
	</div>
	<h1>
		<?= $i18n->_('insert bills') ?>
	</h1>
	<div class="notice">

		<?php /*
		<span><?= $i18n->_('bitcoins will be sent to:') ?></span>
		<div class="address"><?= $ticket->getCustomerAddress()->get() ?></div>

 		*/ ?>

		<div class="button-wrapper">
			<button id="buy" disabled="disabled">
				send money
			</button>
		</div>

		<div><?= $transfer['estimatedFiatQuote']['name'] ?></div>

		<div>
			<?php
				foreach ($transfer['estimatedFiatQuote']['requiredInfo'] as $requiredInfo) {
					echo '<div>';
					echo $requiredInfo['name'];
					echo ': ';
					echo $transfer['requiredInfo'][$requiredInfo['id']];
					echo '</div>';
				}
			?>
		</div>





	</div>
	<div id="running-total">
		<div id="low-balance">
			<?= $i18n->_('Do Not Insert Bills Larger than') ?> <?= $currencyMeta->getSymbol() ?><span id="remainder"></span>
		</div>

		<div>Inserted: <span id="bills">0</span> <?= $currencyMeta->getISOCode() ?></div>
		<div>Recipient: <span id="estimatedExitAmount">0</span> PHP</div>

		<div><span id="btc">0</span> <?= $i18n->_('BTC') ?></div>

	</div>



</div>
<div id="footer">
	<a href="" id="help" class="button">?</a>
</div>
<?php
$scripts = [
	'/assets/gettext/Gettext.js',
	'/settings.js',
	'/assets/jQuery/jquery.min.js',
	'/assets/js/helper.js',
	'/assets/js/Comet.js',
	'/assets/Messi/messi.min.js',
	'/assets/js/loading.js',
	'/assets/js/HelpPanel.js',
	'/assets/coinee/js/purchase.js',
];
include '../foot.phtml';
