<?php
$title = 'Project Skyhook';
$styles = ['/assets/css/skyhook.css', '/assets/coinee/css/start.css'];
$classes = ['start'];
include 'head.phtml';
?>
<style type="text/css">
	html.start body{
		background-image: url('<?= Localization::url('images/Bitcoin-Logo.png') ?>');
	}
</style>


<div class="half-screen buy-btc">
	<p class="start-text">
		buy bitcoin
		<br />
		(
		<span class="crypto-amount">1 <?= $i18n->_('bitcoin') ?></span>
		=
		<span class="fiat-amount"><?= $i18n->_('...') ?></span>
		)
	</p>
	<img class="start-logo" src="./assets/coinee/images/bitcoin.png" />
</div>

<div class="half-screen coinee">
	<p class="start-text">
		send money with Coinee
	</p>
	<img class="start-logo" src="./assets/coinee/images/logo.png" />
</div>


<a href="#" id="language-selector" class="button">
	<img src="<?= Localization::flagURL() ?>" alt="" />
</a>
<div id="help-panel">
	<?= file_get_contents(Localization::path("help.html")); ?>
	<a href="#" class="closer button">&times;</a>
</div>
<!--<div class="price">-->
<!--	<div class="crypto-amount">1 --><?//= $i18n->_('bitcoin') ?><!--</div>-->
<!--	<div class="fiat-amount">--><?//= $i18n->_('...') ?><!--</div>-->
<!--</div>-->
<div id="footer">
	<a href="" id="help" class="button">?</a>
</div>
<?php
$scripts = [
	'/assets/cookies/dist/cookies.min.js',
	'/assets/gettext/Gettext.js',
	'/settings.js',
	'/assets/jQuery/jquery.min.js',
	'/assets/js/helper.js',
	'/assets/js/Comet.js',
	'/assets/js/HelpPanel.js',
	'/assets/js/start.js',
	'/assets/js/NetworkTest.js',
	'/assets/coinee/js/start.js'
];
include 'foot.phtml';
